export const PIPELINE_STEPS = [
  {
    id: 'ingest',
    title: 'Multi-file intake',
    subtitle: 'PDF · PPTX · DOCX · TXT',
    detail: 'Extract text, slide notes, source images, page boundaries and file metadata.',
  },
  {
    id: 'clean',
    title: 'Clean & segment',
    subtitle: 'Evidence units',
    detail: 'Remove duplicate headers and separate rules, tables, examples, warnings and visuals.',
  },
  {
    id: 'analyze',
    title: 'Content analyst',
    subtitle: 'Concept + risk map',
    detail: 'Identify clinical decisions, exclusions, ordered steps, critical thresholds and likely errors.',
  },
  {
    id: 'design',
    title: 'Learning architect',
    subtitle: 'Adaptive plan',
    detail: 'Sequence explanation, worked examples, visuals, practice and targeted remediation.',
  },
  {
    id: 'generate',
    title: 'Activity designer',
    subtitle: 'Quiz · lab · coaching',
    detail: 'Generate grounded activities with diagnostic distractors and source-linked feedback.',
  },
  {
    id: 'review',
    title: 'Quality reviewer',
    subtitle: 'Human approval',
    detail: 'Cross-check each rule against the source package and hold publication for trainer approval.',
  },
];

export const SAMPLE_DOCUMENT = {
  id: 'potassium-source-package',
  filename: 'Potassium Protocol source package (4 learning files)',
  displayName: 'Hemodialysis Potassium Protocol',
  fileType: 'Mixed',
  pages: 42,
  extractedWords: 7384,
  retainedWords: 6281,
  qualityScore: 96,
  sourceUpdated: 'March–June 2025',
  sourceNote: 'Four-file, source-grounded showcase package processed without an external AI API.',
  files: [
    { name: 'Potassium Protocol (Updated - WRHN).pptx', units: '24 slides', purpose: 'Core directive, workflow and documentation screenshots' },
    { name: 'Extra potassium protocol practice questions.pptx', units: '8 slides', purpose: 'Worked clinical cases and answer logic' },
    { name: 'Potassium Protocol Chart with Instructions (Updated).pdf', units: '2 pages', purpose: 'Adjustment table and first/second change instructions' },
    { name: 'ORN Nutrition Fact Sheet - Potassium.pdf', units: '8 pages', purpose: 'Patient education, serving guidance and food choices' },
  ],
};

export const SAMPLE_ANALYSIS = {
  title: 'Potassium Protocol: Assess, Adjust, Document & Follow Up',
  description:
    'A high-fidelity module that teaches hemodialysis nurses when to draw electrolytes, who is eligible for the adjustment table, how to select the correct potassium concentrate, how the first and second consecutive changes differ, what to document, and how to coach patients about dietary potassium.',
  audience: 'Hemodialysis nurses in orientation or annual review',
  estimatedMinutes: 38,
  difficulty: 'Applied clinical practice',
  confidence: 0.96,
  topics: [
    { name: 'Eligibility gate', weight: 98 },
    { name: 'Adjustment table', weight: 98 },
    { name: 'First vs second change', weight: 96 },
    { name: 'Documentation workflow', weight: 91 },
    { name: 'Critical notification', weight: 88 },
    { name: 'Nutrition coaching', weight: 84 },
  ],
  objectives: [
    {
      id: 'obj-1',
      text: 'Recognize clinical changes that require pre-dialysis electrolytes and timely result review.',
      source: 'Core deck · Slides 4, 7–8',
    },
    {
      id: 'obj-2',
      text: 'Confirm all eligibility criteria before using the potassium adjustment table.',
      source: 'Protocol chart · Page 2; core deck · Slides 4–5',
    },
    {
      id: 'obj-3',
      text: 'Select the indicated 1K, 2K or 3K concentrate from the current prescription and serum potassium.',
      source: 'Protocol chart · Page 1; core deck · Slide 10',
    },
    {
      id: 'obj-4',
      text: 'Distinguish an initial temporary change from a second consecutive ongoing change.',
      source: 'Protocol chart · Page 2; core deck · Slides 11–12',
    },
    {
      id: 'obj-5',
      text: 'Complete the machine, order, observation, progress-note and follow-up documentation.',
      source: 'Core deck · Slides 14–18',
    },
    {
      id: 'obj-6',
      text: 'Give source-based potassium nutrition coaching using serving size, preparation and safer substitutions.',
      source: 'ORN nutrition fact sheet · Pages 2–8',
    },
  ],
  moduleSections: [
    {
      id: 'section-1',
      title: 'Why potassium decisions matter',
      type: 'Guided reading',
      minutes: 4,
      summary: 'Purpose, symptoms, draw triggers, lab handling and critical notification thresholds.',
      source: 'Core deck · Slides 3–8',
    },
    {
      id: 'section-2',
      title: 'The eligibility safety gate',
      type: 'Decision tree',
      minutes: 5,
      summary: 'Outpatient ICHD, exactly three treatments weekly, chronic order, no ileostomy and no provider exclusion.',
      source: 'Protocol chart · Page 2',
    },
    {
      id: 'section-3',
      title: 'Potassium decision lab',
      type: 'Interactive calculator',
      minutes: 7,
      summary: 'Apply the adjustment matrix to worked cases and explain why the selected concentrate is correct.',
      source: 'Protocol chart · Page 1; practice deck · Slides 2–8',
    },
    {
      id: 'section-4',
      title: 'Temporary to ongoing',
      type: 'Process flowchart',
      minutes: 5,
      summary: 'Follow the first indicated change, next-treatment reset and second consecutive permanent change.',
      source: 'Core deck · Slides 11–12; protocol chart · Page 2',
    },
    {
      id: 'section-5',
      title: 'Document the decision',
      type: 'Screenshot walkthrough',
      minutes: 6,
      summary: 'Use authentic source screenshots to rehearse the required charting sequence.',
      source: 'Core deck · Slides 14–18',
    },
    {
      id: 'section-6',
      title: 'Coach the patient',
      type: 'Nutrition coaching',
      minutes: 5,
      summary: 'Connect serving size, draining liquids, treatment completion, double-boiling and food substitutions.',
      source: 'ORN nutrition fact sheet · Pages 2–8',
    },
    {
      id: 'section-7',
      title: 'Adaptive clinical assessment',
      type: 'Diagnostic assessment',
      minutes: 6,
      summary: 'Eight source-grounded questions generate topic-specific explanations and focused retesting.',
      source: 'All four learning sources',
    },
  ],
  visualOpportunities: [
    {
      format: 'Decision table',
      score: 100,
      title: 'Potassium concentrate adjustment matrix',
      reason: 'The official matrix is the central clinical decision aid and is included as a source image.',
      image: '/assets/potassium/adjustment-table.png',
    },
    {
      format: 'Branching decision tree',
      score: 98,
      title: 'Can I use the protocol table?',
      reason: 'Five eligibility checks must be passed before the table can be used.',
    },
    {
      format: 'Process timeline',
      score: 97,
      title: 'Initial change → next run → second consecutive change',
      reason: 'The directive changes what is temporary and what becomes the ongoing prescription.',
    },
    {
      format: 'Screenshot simulation',
      score: 95,
      title: 'Cerner and paper documentation walkthrough',
      reason: 'The source deck contains real examples of each required documentation location.',
      image: '/assets/potassium/bath-changed.png',
    },
    {
      format: 'Patient coaching visual',
      score: 89,
      title: 'Double-boiling and potassium food choices',
      reason: 'The nutrition source contains illustrated preparation and substitution guidance.',
      image: '/assets/potassium/double-boil-guide.png',
    },
  ],
  documentQuality: {
    totalChunks: 89,
    usableChunks: 78,
    skippedChunks: 11,
    averageScore: 94,
    skippedReasons: ['Repeated health-system branding', 'Decorative title graphics', 'Cached thumbnail duplicates'],
  },
};

export const SAMPLE_FLOW = [
  {
    step: '01',
    role: 'Safety gate',
    title: 'Confirm table eligibility',
    body: 'Use the adjustment table only for an outpatient in-centre hemodialysis patient dialyzing three times weekly with a chronic order, no ileostomy and no active provider exclusion.',
    completion: 'Every eligibility condition is confirmed. If any condition fails, contact or follow the provider-directed plan instead of applying the table.',
    source: 'Protocol chart · Page 2',
  },
  {
    step: '02',
    role: 'Initial indicated change',
    title: 'Change the current run temporarily',
    body: 'Program the indicated concentrate for the remainder of the current treatment and complete all required documentation.',
    completion: 'The next treatment starts on the previously prescribed concentrate and follow-up electrolytes are collected.',
    source: 'Core deck · Slide 11; protocol chart · Page 2',
  },
  {
    step: '03',
    role: 'Follow-up result',
    title: 'Apply the table again',
    body: 'At the next treatment, use the new potassium result with the prescribed starting concentrate to decide whether the same change is indicated again.',
    completion: 'The result either supports returning to the prescription or confirms a second consecutive indicated change.',
    source: 'Core deck · Slides 11–12',
  },
  {
    step: '04',
    role: 'Second consecutive change',
    title: 'Make the concentrate ongoing',
    body: 'When the follow-up result indicates the same change again, update the standing dialysis order and document the ongoing change.',
    completion: 'The current HD order and all protocol documentation reflect the new ongoing concentrate.',
    source: 'Core deck · Slide 12; protocol chart · Page 2',
  },
];

export const SAMPLE_FLASHCARDS = [
  {
    id: 'fc-1',
    front: 'Who may use the adjustment table?',
    back: 'An outpatient in-centre hemodialysis patient dialyzing three times weekly with a chronic order, no ileostomy and no provider-directed exclusion.',
    topic: 'Eligibility',
    source: 'Protocol chart · Page 2',
    quality: 99,
  },
  {
    id: 'fc-2',
    front: 'What concentrate is indicated when potassium is 5.5 mmol/L or higher?',
    back: '1K, regardless of whether the current prescription is 1K, 2K or 3K.',
    topic: 'Adjustment table',
    source: 'Protocol chart · Page 1',
    quality: 99,
  },
  {
    id: 'fc-3',
    front: 'A patient starts on 1K and the potassium result is 5.1. What does the table indicate?',
    back: 'Remain on 1K. In the 4.8–5.4 row, current 1K maps to 1K.',
    topic: 'Adjustment table',
    source: 'Protocol chart · Page 1; core deck · Slide 20',
    quality: 98,
  },
  {
    id: 'fc-4',
    front: 'What happens after the first indicated concentrate change?',
    back: 'The change is temporary for the remainder of the current run. The next treatment starts on the prescribed concentrate and follow-up electrolytes are drawn.',
    topic: 'Change sequence',
    source: 'Core deck · Slide 11',
    quality: 99,
  },
  {
    id: 'fc-5',
    front: 'When does the new concentrate become ongoing?',
    back: 'When the follow-up result at the next treatment indicates the same change a second consecutive time.',
    topic: 'Change sequence',
    source: 'Core deck · Slide 12',
    quality: 99,
  },
  {
    id: 'fc-6',
    front: 'Which potassium values require immediate provider notification?',
    back: 'Potassium below 3.0 mmol/L or above 6.5 mmol/L.',
    topic: 'Critical notification',
    source: 'Protocol chart · Pages 1–2',
    quality: 100,
  },
  {
    id: 'fc-7',
    front: 'Name the core documentation locations after a bath change.',
    back: 'Machine settings, Observations “Bath Changed,” Day Hemo/Current HD order as applicable, written Order for Treatment, Progress Note “Potassium Protocol,” and follow-up lytes order.',
    topic: 'Documentation',
    source: 'Core deck · Slides 14–18',
    quality: 96,
  },
  {
    id: 'fc-8',
    front: 'What practical nutrition advice reduces potassium intake from prepared foods?',
    back: 'Watch serving size, drain and discard liquids from canned/cooked/frozen foods, complete prescribed dialysis, and use the source’s double-boiling method for root vegetables.',
    topic: 'Nutrition',
    source: 'ORN nutrition fact sheet · Pages 2–4',
    quality: 95,
  },
];

export const SAMPLE_QUIZ = [
  {
    id: 'q-1',
    topic: 'Eligibility',
    question: 'Kurtis receives in-centre hemodialysis four times per week. He reports weakness and has potassium 5.5 mmol/L. What is the safest protocol action?',
    options: [
      'Use the table and change to 1K because the value is 5.5',
      'Use the table only for the current run, then call the provider',
      'Do not use the adjustment table because he is not on a three-times-weekly schedule',
      'No action is needed because weakness is not a draw trigger',
    ],
    correct: 2,
    explanation:
      'The eligibility gate comes before the potassium value. The adjustment table is limited to outpatient in-centre patients dialyzing exactly three times weekly.',
    source: 'Practice deck · Slide 5; protocol chart · Page 2',
    quality: 100,
    diagnostic: {
      topic: 'Eligibility',
      misconception: 'You applied the potassium number before checking whether the patient qualifies for the table.',
      coaching: 'Always run the five-part eligibility gate first. A correct table lookup is still unsafe when the patient is outside the directive.',
      visual: '/assets/potassium/adjustment-table.png',
    },
  },
  {
    id: 'q-2',
    topic: 'Adjustment table',
    question: 'Jenny is eligible, currently prescribed 1K, and her potassium is 5.1 mmol/L. What does the table indicate?',
    options: ['Change to 3K', 'Change to 2K', 'Remain on 1K', 'Notify the provider because 5.1 is critical'],
    correct: 2,
    explanation:
      'In the 4.8–5.4 row, the 1K column remains 1K. Read both the result row and the current-prescription column.',
    source: 'Core deck · Slide 20; protocol chart · Page 1',
    quality: 100,
    diagnostic: {
      topic: 'Adjustment table',
      misconception: 'You read the potassium range without following the current-prescription column.',
      coaching: 'The matrix is a two-axis decision: find the potassium row, then stay in the patient’s current 1K/2K/3K column.',
      visual: '/assets/potassium/adjustment-table.png',
    },
  },
  {
    id: 'q-3',
    topic: 'First vs second change',
    question: 'Hannah starts on prescribed 1K. Routine potassium is 4.7 mmol/L and the table indicates 3K. What happens now?',
    options: [
      'Change permanently to 3K before the next treatment',
      'Use 3K for the remainder of this run; next run starts on 1K with repeat electrolytes',
      'Continue 1K because only high potassium can trigger a change',
      'Use 2K for one run as an intermediate step',
    ],
    correct: 1,
    explanation:
      'The first indicated change is temporary for the remainder of the current treatment. The next treatment begins on the prescribed 1K and follow-up electrolytes are collected.',
    source: 'Practice deck · Slide 3; core deck · Slide 11',
    quality: 100,
    diagnostic: {
      topic: 'First vs second change',
      misconception: 'You treated the first indicated change as an ongoing prescription.',
      coaching: 'Think “first = temporary test, second consecutive = ongoing change.” The reset at the next run is deliberate.',
      visual: '/assets/potassium/day-hemo-order.png',
    },
  },
  {
    id: 'q-4',
    topic: 'First vs second change',
    question: 'At Hannah’s next treatment she starts on the prescribed 1K. Repeat potassium is 4.5 mmol/L, again indicating 3K. What is the correct action?',
    options: [
      'Change to 3K as the ongoing prescription and update the standing order',
      'Use 3K temporarily again but keep the standing order at 1K indefinitely',
      'Change to 2K because two changes must be gradual',
      'Stop using the protocol because this is a repeat result',
    ],
    correct: 0,
    explanation:
      'This is the second consecutive result indicating the same change, so 3K becomes ongoing and the current dialysis order is updated.',
    source: 'Practice deck · Slide 4; core deck · Slide 12',
    quality: 100,
    diagnostic: {
      topic: 'First vs second change',
      misconception: 'You missed the point at which a repeated indication becomes the ongoing order.',
      coaching: 'At the follow-up run, the same indicated change for a second consecutive time converts the temporary trial into the standing prescription.',
      visual: '/assets/potassium/follow-up-lytes.png',
    },
  },
  {
    id: 'q-5',
    topic: 'Critical notification',
    question: 'An eligible patient’s potassium result is 6.6 mmol/L. Which action must occur in addition to any table-directed response?',
    options: [
      'Document it at the end of the shift',
      'Immediately notify the most responsible provider',
      'Repeat the level at the next monthly bloodwork',
      'Only notify if the current concentrate is 3K',
    ],
    correct: 1,
    explanation:
      'The protocol requires provider notification for potassium below 3.0 mmol/L or above 6.5 mmol/L.',
    source: 'Protocol chart · Pages 1–2',
    quality: 100,
    diagnostic: {
      topic: 'Critical notification',
      misconception: 'You treated the adjustment table as a replacement for critical-result communication.',
      coaching: 'The table directs concentrate selection; the critical threshold separately triggers immediate provider notification.',
      visual: '/assets/potassium/adjustment-table.png',
    },
  },
  {
    id: 'q-6',
    topic: 'Documentation',
    question: 'Which documentation item specifically records that the dialysis bath was changed during treatment?',
    options: [
      'Observations: “Bath Changed”',
      'Nutrition referral',
      'Medication administration record',
      'Discharge summary',
    ],
    correct: 0,
    explanation:
      'The source instructs the nurse to select “Bath Changed” in Observations as part of the documentation bundle.',
    source: 'Core deck · Slide 16',
    quality: 99,
    diagnostic: {
      topic: 'Documentation',
      misconception: 'You chose a chart location that does not capture the protocol-specific bath change.',
      coaching: 'Anchor the sequence to the source screenshots: machine settings, Observations, orders, Progress Note and follow-up lytes.',
      visual: '/assets/potassium/bath-changed.png',
    },
  },
  {
    id: 'q-7',
    topic: 'Nutrition',
    question: 'Which patient statement best reflects the nutrition fact sheet?',
    options: [
      '“If a food is lower in potassium, serving size no longer matters.”',
      '“I should save the liquid from canned vegetables because potassium stays in the food.”',
      '“Double-boiling can lower potassium in root vegetables, but portion size still matters.”',
      '“Everyone with kidney disease should avoid all potassium foods.”',
    ],
    correct: 2,
    explanation:
      'The fact sheet emphasizes serving size and describes double-boiling as a way to reduce potassium—not to make unlimited portions safe.',
    source: 'ORN nutrition fact sheet · Pages 2–4',
    quality: 98,
    diagnostic: {
      topic: 'Nutrition',
      misconception: 'You interpreted preparation advice as permission to ignore portions or individual lab guidance.',
      coaching: 'Nutrition coaching combines the patient’s blood level, portion size, preparation method and individualized dietitian advice.',
      visual: '/assets/potassium/double-boil-guide.png',
    },
  },
  {
    id: 'q-8',
    topic: 'Eligibility',
    question: 'Sean receives dialysis at a satellite site three times weekly and has potassium 5.4 mmol/L. May the nurse use the adjustment table?',
    options: [
      'Yes, because his schedule is three times weekly',
      'Yes, but only if he currently uses 2K',
      'No; satellite patients are excluded from table-directed adjustment',
      'No, because 5.4 is a critical value',
    ],
    correct: 2,
    explanation:
      'The source’s table-directed pathway is for in-centre hemodialysis outpatients and excludes satellite patients.',
    source: 'Practice deck · Slide 6; core deck · Slide 5',
    quality: 99,
    diagnostic: {
      topic: 'Eligibility',
      misconception: 'You checked treatment frequency but missed the care-location exclusion.',
      coaching: 'Eligibility is an all-conditions gate. Three treatments weekly is necessary, but it is not sufficient.',
      visual: '/assets/potassium/adjustment-table.png',
    },
  },
];

export const SAMPLE_SCENARIO = {
  id: 'scenario-1',
  title: 'Ted’s two-treatment decision',
  prompt:
    'Ted is an eligible outpatient on prescribed 2K. After 36 hours of diarrhea and new weakness, potassium is 4.5 mmol/L. The same 4.5 result is obtained at the next treatment after he starts again on prescribed 2K. What sequence is correct?',
  options: [
    'First run: temporary 3K; next run: start 2K, repeat lytes; second consecutive result: ongoing 3K',
    'First run: ongoing 3K; next run: no repeat lytes',
    'First run: remain 2K; next run: notify only if potassium is above 6.5',
    'First run: temporary 1K; next run: ongoing 1K',
  ],
  correct: 0,
  explanation:
    'The symptoms justify the draw. On current 2K, potassium 4.5 maps to 3K. The first change is temporary; the repeated indication at the next run makes 3K ongoing.',
  source: 'Core deck · Slides 21–23',
  quality: 100,
};

export const REMEDIATION_PACKS = {
  Eligibility: {
    title: 'Use the safety gate before the table',
    summary: 'Your answer suggests that you jumped directly to the potassium value.',
    principle: 'The patient must pass every eligibility condition before any table cell is used.',
    source: 'Protocol chart · Page 2; core deck · Slides 4–5',
    visual: '/assets/potassium/adjustment-table.png',
    checks: [
      {
        question: 'Which patient is eligible for the table?',
        options: ['Satellite patient, three times weekly', 'In-centre outpatient, three times weekly, chronic order, no exclusions', 'In-centre outpatient, four times weekly'],
        correct: 1,
        explanation: 'All five gate conditions are present only in the second option.',
      },
      {
        question: 'An in-centre patient has an ileostomy. What should you do?',
        options: ['Use the table normally', 'Do not use the table-directed pathway', 'Use only the 1K column'],
        correct: 1,
        explanation: 'Ileostomy is a stated exclusion from table-directed adjustment.',
      },
    ],
  },
  'Adjustment table': {
    title: 'Read the matrix on two axes',
    summary: 'Your answer suggests that you used the potassium range but lost the current-prescription column.',
    principle: 'Find the result row first, then trace across the patient’s current 3K, 2K or 1K column.',
    source: 'Protocol chart · Page 1',
    visual: '/assets/potassium/adjustment-table.png',
    checks: [
      {
        question: 'Current 2K with potassium 5.2 mmol/L maps to:',
        options: ['1K', '2K', '3K'],
        correct: 1,
        explanation: 'In the 4.8–5.4 row, current 2K remains 2K.',
      },
      {
        question: 'Current 3K with potassium 5.6 mmol/L maps to:',
        options: ['1K', '2K', '3K'],
        correct: 0,
        explanation: 'At 5.5 or higher, every current-prescription column maps to 1K.',
      },
    ],
  },
  'First vs second change': {
    title: 'Separate temporary from ongoing',
    summary: 'Your answer suggests that the reset-and-recheck sequence was unclear.',
    principle: 'First indicated change = remainder of this run. Second consecutive indicated change = update the ongoing order.',
    source: 'Core deck · Slides 11–12; protocol chart · Page 2',
    visual: '/assets/potassium/follow-up-lytes.png',
    checks: [
      {
        question: 'After an initial temporary change, what bath starts the next treatment?',
        options: ['The temporary bath', 'The previously prescribed bath', 'Always 2K'],
        correct: 1,
        explanation: 'The patient starts the next treatment on the prescribed concentrate before follow-up lytes are applied.',
      },
      {
        question: 'When is the standing order updated?',
        options: ['At the first indicated change', 'After the second consecutive indicated change', 'Only at annual review'],
        correct: 1,
        explanation: 'A repeated indication at the follow-up treatment makes the change ongoing.',
      },
    ],
  },
  'Critical notification': {
    title: 'Keep the notification threshold separate',
    summary: 'Your answer suggests that table action and critical communication were blended together.',
    principle: 'Notify the provider immediately below 3.0 or above 6.5 mmol/L, even while following the protocol response.',
    source: 'Protocol chart · Pages 1–2',
    visual: '/assets/potassium/adjustment-table.png',
    checks: [
      {
        question: 'Which value requires immediate provider notification?',
        options: ['3.2', '5.8', '6.6'],
        correct: 2,
        explanation: 'Above 6.5 mmol/L meets the source’s notification threshold.',
      },
      {
        question: 'Does a table-directed bath change replace provider notification for a critical result?',
        options: ['Yes', 'No'],
        correct: 1,
        explanation: 'They are separate required actions.',
      },
    ],
  },
  Documentation: {
    title: 'Chart the full protocol trail',
    summary: 'Your answer suggests that one of the protocol-specific documentation locations was missed.',
    principle: 'The record should make the result, decision, machine change, order status and follow-up plan visible.',
    source: 'Core deck · Slides 14–18',
    visual: '/assets/potassium/bath-changed.png',
    checks: [
      {
        question: 'Where is “Bath Changed” selected?',
        options: ['Observations', 'Medication record', 'Nutrition note'],
        correct: 0,
        explanation: 'The screenshot places the checkbox in Observations.',
      },
      {
        question: 'Which order supports the next-run repeat test?',
        options: ['K Protocol Follow Up Lytes', 'Discharge medication reconciliation', 'Annual care-map order'],
        correct: 0,
        explanation: 'The source names the follow-up electrolyte order directly.',
      },
    ],
  },
  Nutrition: {
    title: 'Coach portions and preparation together',
    summary: 'Your answer suggests that one nutrition technique was treated as an unlimited rule.',
    principle: 'Serving size still matters, and restriction should reflect the patient’s blood levels and renal dietitian plan.',
    source: 'ORN nutrition fact sheet · Pages 2–8',
    visual: '/assets/potassium/double-boil-guide.png',
    checks: [
      {
        question: 'What should happen to liquid from canned vegetables?',
        options: ['Serve it', 'Drain and discard it', 'Use it only on dialysis days'],
        correct: 1,
        explanation: 'The fact sheet advises discarding canned, cooked and frozen food liquids.',
      },
      {
        question: 'Does double-boiling make root vegetables unlimited?',
        options: ['Yes', 'No'],
        correct: 1,
        explanation: 'It lowers potassium, but the food is not automatically low-potassium and portions still matter.',
      },
    ],
  },
};

export const STUDENTS = [
  {
    id: 'emma',
    name: 'Emma Thompson',
    initials: 'ET',
    cohort: '2026 Spring',
    status: 'At risk',
    completion: 72,
    average: 63,
    time: '5h 06m',
    lastActive: 'Today',
    currentModule: 'Potassium Protocol',
    strengths: ['Draw triggers', 'Critical notification'],
    weaknesses: ['Eligibility gate', 'First vs second change'],
    mastery: [
      { topic: 'Draw triggers', score: 91 },
      { topic: 'Eligibility', score: 42 },
      { topic: 'Table reading', score: 68 },
      { topic: 'Change sequence', score: 39 },
      { topic: 'Documentation', score: 74 },
      { topic: 'Nutrition', score: 82 },
    ],
    recommendation:
      'Assign the two-question eligibility gate and temporary-versus-ongoing remediation packs before the final retry.',
    attempts: 3,
    evidence: [
      {
        topic: 'Eligibility gate',
        prompt: 'Kurtis receives hemodialysis four times weekly and has potassium 5.5.',
        selected: 'Use the table and change to 1K.',
        diagnosis: 'Applied the potassium number before confirming treatment-frequency eligibility.',
        assigned: 'Safety gate micro-lesson + 2 focused questions',
      },
      {
        topic: 'First vs second change',
        prompt: 'Hannah’s first result indicates a change from prescribed 1K to 3K.',
        selected: 'Change permanently to 3K.',
        diagnosis: 'Confused the initial temporary change with the second consecutive ongoing change.',
        assigned: 'Reset-and-recheck timeline + 2 focused questions',
      },
    ],
  },
  {
    id: 'liam',
    name: 'Liam Okafor',
    initials: 'LO',
    cohort: '2026 Spring',
    status: 'Active',
    completion: 48,
    average: 84,
    time: '3h 34m',
    lastActive: 'Yesterday',
    currentModule: 'Potassium Protocol',
    strengths: ['Eligibility', 'Adjustment table'],
    weaknesses: ['Documentation sequence'],
    mastery: [
      { topic: 'Draw triggers', score: 86 },
      { topic: 'Eligibility', score: 90 },
      { topic: 'Table reading', score: 88 },
      { topic: 'Change sequence', score: 81 },
      { topic: 'Documentation', score: 61 },
      { topic: 'Nutrition', score: 79 },
    ],
    recommendation: 'Assign the documentation screenshot walkthrough and one charting-sequence retry.',
    attempts: 1,
    evidence: [],
  },
  {
    id: 'priya',
    name: 'Priya Nair',
    initials: 'PN',
    cohort: '2026 Winter',
    status: 'On track',
    completion: 91,
    average: 94,
    time: '9h 21m',
    lastActive: 'Today',
    currentModule: 'Complications & Monitoring',
    strengths: ['Eligibility', 'Clinical application', 'Patient coaching'],
    weaknesses: ['None currently detected'],
    mastery: [
      { topic: 'Draw triggers', score: 96 },
      { topic: 'Eligibility', score: 94 },
      { topic: 'Table reading', score: 92 },
      { topic: 'Change sequence', score: 96 },
      { topic: 'Documentation', score: 90 },
      { topic: 'Nutrition', score: 88 },
    ],
    recommendation: 'Offer the advanced two-treatment Ted scenario and allow progression.',
    attempts: 1,
    evidence: [],
  },
  {
    id: 'noah',
    name: 'Noah Williams',
    initials: 'NW',
    cohort: '2026 Spring',
    status: 'Inactive',
    completion: 17,
    average: 64,
    time: '1h 09m',
    lastActive: '9 days ago',
    currentModule: 'Fluid Volume Calculation',
    strengths: ['Basic terminology'],
    weaknesses: ['Engagement', 'Safety thresholds', 'Documentation'],
    mastery: [
      { topic: 'Draw triggers', score: 70 },
      { topic: 'Eligibility', score: 61 },
      { topic: 'Table reading', score: 48 },
      { topic: 'Change sequence', score: 58 },
      { topic: 'Documentation', score: 46 },
      { topic: 'Nutrition', score: 67 },
    ],
    recommendation: 'Trainer check-in recommended; assign a guided 10-minute restart plan.',
    attempts: 4,
    evidence: [],
  },
];

export const COHORT_MASTERY = [
  { topic: 'Clinical draw triggers', score: 88, trend: '+6%' },
  { topic: 'Critical notification', score: 86, trend: '+4%' },
  { topic: 'Nutrition coaching', score: 79, trend: '+3%' },
  { topic: 'Adjustment-table reading', score: 71, trend: '-2%' },
  { topic: 'Eligibility gate', score: 58, trend: '-6%' },
  { topic: 'First vs second change', score: 52, trend: '-9%' },
];

export function buildSampleResult() {
  return {
    source: SAMPLE_DOCUMENT,
    analysis: SAMPLE_ANALYSIS,
    flow: SAMPLE_FLOW,
    flashcards: SAMPLE_FLASHCARDS,
    quiz: SAMPLE_QUIZ,
    scenario: SAMPLE_SCENARIO,
    remediation: REMEDIATION_PACKS,
    generatedAt: new Date().toISOString(),
    generationMethod: 'Cached four-source demonstration result with diagnostic remediation',
  };
}
